/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AuditEntry {
  'id' : bigint,
  'action' : string,
  'performedBy' : bigint,
  'timestamp' : Time,
  'details' : string,
  'targetEntity' : string,
}
export interface Brand {
  'id' : bigint,
  'name' : string,
  'isActive' : boolean,
  'category' : string,
}
export interface InventoryItem {
  'id' : bigint,
  'sku' : string,
  'name' : string,
  'unit' : string,
  'lastUpdated' : Time,
  'quantityOnHand' : bigint,
  'minStock' : bigint,
  'warehouseLocation' : string,
  'category' : string,
}
export interface MOQItem {
  'id' : bigint,
  'unit' : string,
  'projectId' : bigint,
  'itemName' : string,
  'quantity' : number,
  'category' : string,
  'brand' : string,
  'unitPrice' : number,
  'totalPrice' : number,
}
export interface Project {
  'id' : bigint,
  'installationType' : { 'sheetMetal' : null } |
    { 'rccRooftop' : null } |
    { 'other' : null } |
    { 'groundMount' : null },
  'status' : ProjectStatus,
  'batteryCapacityKWh' : number,
  'clientName' : string,
  'loadInputMethod' : { 'applianceBased' : null } |
    { 'consumptionBased' : null },
  'systemSizeKW' : number,
  'systemType' : { 'hybrid' : null } |
    { 'offGrid' : null } |
    { 'onGrid' : null },
}
export type ProjectStatus = { 'completed' : null } |
  { 'approved' : null } |
  { 'quoted' : null } |
  { 'draft' : null } |
  { 'inProgress' : null };
export interface Quotation {
  'id' : bigint,
  'gst' : number,
  'irr' : number,
  'status' : QuotationStatus,
  'subsidy' : number,
  'clientName' : string,
  'paybackYears' : number,
  'proposalNumber' : string,
  'totalCost' : number,
  'carbonSavings' : number,
  'annualSavings' : number,
  'termsAndConditions' : string,
  'companyName' : string,
}
export type QuotationStatus = { 'sent' : null } |
  { 'rejected' : null } |
  { 'accepted' : null } |
  { 'draft' : null };
export type Time = bigint;
export interface User {
  'id' : bigint,
  'name' : string,
  'role' : UserRole,
  'isActive' : boolean,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'owner' : null } |
  { 'procurement' : null } |
  { 'siteEngineer' : null };
export interface _SERVICE {
  'addAppliance' : ActorMethod<
    [bigint, string, number, number, number, bigint],
    bigint
  >,
  'addAuditEntry' : ActorMethod<[string, bigint, string, string], undefined>,
  'createBrand' : ActorMethod<[string, string, boolean], bigint>,
  'createInventoryItem' : ActorMethod<
    [string, string, string, bigint, bigint, string, string],
    bigint
  >,
  'createProject' : ActorMethod<
    [
      string,
      { 'hybrid' : null } |
        { 'offGrid' : null } |
        { 'onGrid' : null },
      { 'sheetMetal' : null } |
        { 'rccRooftop' : null } |
        { 'other' : null } |
        { 'groundMount' : null },
      { 'applianceBased' : null } |
        { 'consumptionBased' : null },
      number,
      number,
    ],
    bigint
  >,
  'createQuotation' : ActorMethod<
    [
      string,
      string,
      string,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      QuotationStatus,
      string,
    ],
    bigint
  >,
  'createUser' : ActorMethod<[string, string, UserRole, boolean], bigint>,
  'getAuditLog' : ActorMethod<[], Array<AuditEntry>>,
  'listBrands' : ActorMethod<[], Array<Brand>>,
  'listInventory' : ActorMethod<[], Array<InventoryItem>>,
  'listMOQ' : ActorMethod<[bigint], Array<MOQItem>>,
  'listProjects' : ActorMethod<[], Array<Project>>,
  'listQuotations' : ActorMethod<[], Array<Quotation>>,
  'listUsers' : ActorMethod<[], Array<User>>,
  'updateMOQItem' : ActorMethod<[bigint, number, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];