/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const QuotationStatus = IDL.Variant({
  'sent' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
  'draft' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'owner' : IDL.Null,
  'procurement' : IDL.Null,
  'siteEngineer' : IDL.Null,
});
export const Time = IDL.Int;
export const AuditEntry = IDL.Record({
  'id' : IDL.Nat,
  'action' : IDL.Text,
  'performedBy' : IDL.Nat,
  'timestamp' : Time,
  'details' : IDL.Text,
  'targetEntity' : IDL.Text,
});
export const Brand = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'category' : IDL.Text,
});
export const InventoryItem = IDL.Record({
  'id' : IDL.Nat,
  'sku' : IDL.Text,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'lastUpdated' : Time,
  'quantityOnHand' : IDL.Nat,
  'minStock' : IDL.Nat,
  'warehouseLocation' : IDL.Text,
  'category' : IDL.Text,
});
export const MOQItem = IDL.Record({
  'id' : IDL.Nat,
  'unit' : IDL.Text,
  'projectId' : IDL.Nat,
  'itemName' : IDL.Text,
  'quantity' : IDL.Float64,
  'category' : IDL.Text,
  'brand' : IDL.Text,
  'unitPrice' : IDL.Float64,
  'totalPrice' : IDL.Float64,
});
export const ProjectStatus = IDL.Variant({
  'completed' : IDL.Null,
  'approved' : IDL.Null,
  'quoted' : IDL.Null,
  'draft' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'installationType' : IDL.Variant({
    'sheetMetal' : IDL.Null,
    'rccRooftop' : IDL.Null,
    'other' : IDL.Null,
    'groundMount' : IDL.Null,
  }),
  'status' : ProjectStatus,
  'batteryCapacityKWh' : IDL.Float64,
  'clientName' : IDL.Text,
  'loadInputMethod' : IDL.Variant({
    'applianceBased' : IDL.Null,
    'consumptionBased' : IDL.Null,
  }),
  'systemSizeKW' : IDL.Float64,
  'systemType' : IDL.Variant({
    'hybrid' : IDL.Null,
    'offGrid' : IDL.Null,
    'onGrid' : IDL.Null,
  }),
});
export const Quotation = IDL.Record({
  'id' : IDL.Nat,
  'gst' : IDL.Float64,
  'irr' : IDL.Float64,
  'status' : QuotationStatus,
  'subsidy' : IDL.Float64,
  'clientName' : IDL.Text,
  'paybackYears' : IDL.Float64,
  'proposalNumber' : IDL.Text,
  'totalCost' : IDL.Float64,
  'carbonSavings' : IDL.Float64,
  'annualSavings' : IDL.Float64,
  'termsAndConditions' : IDL.Text,
  'companyName' : IDL.Text,
});
export const User = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'role' : UserRole,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAppliance' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'addAuditEntry' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text, IDL.Text], [], []),
  'createBrand' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [IDL.Nat], []),
  'createInventoryItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createProject' : IDL.Func(
      [
        IDL.Text,
        IDL.Variant({
          'hybrid' : IDL.Null,
          'offGrid' : IDL.Null,
          'onGrid' : IDL.Null,
        }),
        IDL.Variant({
          'sheetMetal' : IDL.Null,
          'rccRooftop' : IDL.Null,
          'other' : IDL.Null,
          'groundMount' : IDL.Null,
        }),
        IDL.Variant({
          'applianceBased' : IDL.Null,
          'consumptionBased' : IDL.Null,
        }),
        IDL.Float64,
        IDL.Float64,
      ],
      [IDL.Nat],
      [],
    ),
  'createQuotation' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        QuotationStatus,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'createUser' : IDL.Func(
      [IDL.Text, IDL.Text, UserRole, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'getAuditLog' : IDL.Func([], [IDL.Vec(AuditEntry)], []),
  'listBrands' : IDL.Func([], [IDL.Vec(Brand)], ['query']),
  'listInventory' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'listMOQ' : IDL.Func([IDL.Nat], [IDL.Vec(MOQItem)], ['query']),
  'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'listQuotations' : IDL.Func([], [IDL.Vec(Quotation)], ['query']),
  'listUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'updateMOQItem' : IDL.Func([IDL.Nat, IDL.Float64, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const QuotationStatus = IDL.Variant({
    'sent' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
    'draft' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'owner' : IDL.Null,
    'procurement' : IDL.Null,
    'siteEngineer' : IDL.Null,
  });
  const Time = IDL.Int;
  const AuditEntry = IDL.Record({
    'id' : IDL.Nat,
    'action' : IDL.Text,
    'performedBy' : IDL.Nat,
    'timestamp' : Time,
    'details' : IDL.Text,
    'targetEntity' : IDL.Text,
  });
  const Brand = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'category' : IDL.Text,
  });
  const InventoryItem = IDL.Record({
    'id' : IDL.Nat,
    'sku' : IDL.Text,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'lastUpdated' : Time,
    'quantityOnHand' : IDL.Nat,
    'minStock' : IDL.Nat,
    'warehouseLocation' : IDL.Text,
    'category' : IDL.Text,
  });
  const MOQItem = IDL.Record({
    'id' : IDL.Nat,
    'unit' : IDL.Text,
    'projectId' : IDL.Nat,
    'itemName' : IDL.Text,
    'quantity' : IDL.Float64,
    'category' : IDL.Text,
    'brand' : IDL.Text,
    'unitPrice' : IDL.Float64,
    'totalPrice' : IDL.Float64,
  });
  const ProjectStatus = IDL.Variant({
    'completed' : IDL.Null,
    'approved' : IDL.Null,
    'quoted' : IDL.Null,
    'draft' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'installationType' : IDL.Variant({
      'sheetMetal' : IDL.Null,
      'rccRooftop' : IDL.Null,
      'other' : IDL.Null,
      'groundMount' : IDL.Null,
    }),
    'status' : ProjectStatus,
    'batteryCapacityKWh' : IDL.Float64,
    'clientName' : IDL.Text,
    'loadInputMethod' : IDL.Variant({
      'applianceBased' : IDL.Null,
      'consumptionBased' : IDL.Null,
    }),
    'systemSizeKW' : IDL.Float64,
    'systemType' : IDL.Variant({
      'hybrid' : IDL.Null,
      'offGrid' : IDL.Null,
      'onGrid' : IDL.Null,
    }),
  });
  const Quotation = IDL.Record({
    'id' : IDL.Nat,
    'gst' : IDL.Float64,
    'irr' : IDL.Float64,
    'status' : QuotationStatus,
    'subsidy' : IDL.Float64,
    'clientName' : IDL.Text,
    'paybackYears' : IDL.Float64,
    'proposalNumber' : IDL.Text,
    'totalCost' : IDL.Float64,
    'carbonSavings' : IDL.Float64,
    'annualSavings' : IDL.Float64,
    'termsAndConditions' : IDL.Text,
    'companyName' : IDL.Text,
  });
  const User = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'role' : UserRole,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
  });
  
  return IDL.Service({
    'addAppliance' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'addAuditEntry' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text, IDL.Text], [], []),
    'createBrand' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [IDL.Nat], []),
    'createInventoryItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createProject' : IDL.Func(
        [
          IDL.Text,
          IDL.Variant({
            'hybrid' : IDL.Null,
            'offGrid' : IDL.Null,
            'onGrid' : IDL.Null,
          }),
          IDL.Variant({
            'sheetMetal' : IDL.Null,
            'rccRooftop' : IDL.Null,
            'other' : IDL.Null,
            'groundMount' : IDL.Null,
          }),
          IDL.Variant({
            'applianceBased' : IDL.Null,
            'consumptionBased' : IDL.Null,
          }),
          IDL.Float64,
          IDL.Float64,
        ],
        [IDL.Nat],
        [],
      ),
    'createQuotation' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          QuotationStatus,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'createUser' : IDL.Func(
        [IDL.Text, IDL.Text, UserRole, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'getAuditLog' : IDL.Func([], [IDL.Vec(AuditEntry)], []),
    'listBrands' : IDL.Func([], [IDL.Vec(Brand)], ['query']),
    'listInventory' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'listMOQ' : IDL.Func([IDL.Nat], [IDL.Vec(MOQItem)], ['query']),
    'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'listQuotations' : IDL.Func([], [IDL.Vec(Quotation)], ['query']),
    'listUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'updateMOQItem' : IDL.Func([IDL.Nat, IDL.Float64, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };