/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface InventoryItem {
    id: bigint;
    sku: string;
    name: string;
    unit: string;
    lastUpdated: Time;
    quantityOnHand: bigint;
    minStock: bigint;
    warehouseLocation: string;
    category: string;
}
export interface Quotation {
    id: bigint;
    gst: number;
    irr: number;
    status: QuotationStatus;
    subsidy: number;
    clientName: string;
    paybackYears: number;
    proposalNumber: string;
    totalCost: number;
    carbonSavings: number;
    annualSavings: number;
    termsAndConditions: string;
    companyName: string;
}
export type Time = bigint;
export interface MOQItem {
    id: bigint;
    unit: string;
    projectId: bigint;
    itemName: string;
    quantity: number;
    category: string;
    brand: string;
    unitPrice: number;
    totalPrice: number;
}
export interface User {
    id: bigint;
    name: string;
    role: UserRole;
    isActive: boolean;
    email: string;
}
export interface AuditEntry {
    id: bigint;
    action: string;
    performedBy: bigint;
    timestamp: Time;
    details: string;
    targetEntity: string;
}
export interface Project {
    id: bigint;
    installationType: Variant_sheetMetal_rccRooftop_other_groundMount;
    status: ProjectStatus;
    batteryCapacityKWh: number;
    clientName: string;
    loadInputMethod: Variant_applianceBased_consumptionBased;
    systemSizeKW: number;
    systemType: Variant_hybrid_offGrid_onGrid;
}
export interface Brand {
    id: bigint;
    name: string;
    isActive: boolean;
    category: string;
}
export enum ProjectStatus {
    completed = "completed",
    approved = "approved",
    quoted = "quoted",
    draft = "draft",
    inProgress = "inProgress"
}
export enum QuotationStatus {
    sent = "sent",
    rejected = "rejected",
    accepted = "accepted",
    draft = "draft"
}
export enum UserRole {
    admin = "admin",
    owner = "owner",
    procurement = "procurement",
    siteEngineer = "siteEngineer"
}
export enum Variant_applianceBased_consumptionBased {
    applianceBased = "applianceBased",
    consumptionBased = "consumptionBased"
}
export enum Variant_hybrid_offGrid_onGrid {
    hybrid = "hybrid",
    offGrid = "offGrid",
    onGrid = "onGrid"
}
export enum Variant_sheetMetal_rccRooftop_other_groundMount {
    sheetMetal = "sheetMetal",
    rccRooftop = "rccRooftop",
    other = "other",
    groundMount = "groundMount"
}
export interface backendInterface {
    addAppliance(projectId: bigint, name: string, wattage: number, surgeFactor: number, dailyHours: number, quantity: bigint): Promise<bigint>;
    addAuditEntry(action: string, performedBy: bigint, targetEntity: string, details: string): Promise<void>;
    createBrand(category: string, name: string, isActive: boolean): Promise<bigint>;
    createInventoryItem(sku: string, name: string, category: string, quantityOnHand: bigint, minStock: bigint, unit: string, warehouseLocation: string): Promise<bigint>;
    createProject(clientName: string, systemType: Variant_hybrid_offGrid_onGrid, installationType: Variant_sheetMetal_rccRooftop_other_groundMount, loadInputMethod: Variant_applianceBased_consumptionBased, systemSizeKW: number, batteryCapacityKWh: number): Promise<bigint>;
    createQuotation(proposalNumber: string, clientName: string, companyName: string, gst: number, totalCost: number, subsidy: number, paybackYears: number, annualSavings: number, irr: number, carbonSavings: number, status: QuotationStatus, termsAndConditions: string): Promise<bigint>;
    createUser(name: string, email: string, role: UserRole, isActive: boolean): Promise<bigint>;
    getAuditLog(): Promise<Array<AuditEntry>>;
    listBrands(): Promise<Array<Brand>>;
    listInventory(): Promise<Array<InventoryItem>>;
    listMOQ(projectId: bigint): Promise<Array<MOQItem>>;
    listProjects(): Promise<Array<Project>>;
    listQuotations(): Promise<Array<Quotation>>;
    listUsers(): Promise<Array<User>>;
    updateMOQItem(id: bigint, quantity: number, unitPrice: number): Promise<void>;
}
import type { Project as _Project, ProjectStatus as _ProjectStatus, Quotation as _Quotation, QuotationStatus as _QuotationStatus, User as _User, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAppliance(arg0: bigint, arg1: string, arg2: number, arg3: number, arg4: number, arg5: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addAppliance(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAppliance(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addAuditEntry(arg0: string, arg1: bigint, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAuditEntry(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAuditEntry(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createBrand(arg0: string, arg1: string, arg2: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBrand(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBrand(arg0, arg1, arg2);
            return result;
        }
    }
    async createInventoryItem(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: string, arg6: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createInventoryItem(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInventoryItem(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async createProject(arg0: string, arg1: Variant_hybrid_offGrid_onGrid, arg2: Variant_sheetMetal_rccRooftop_other_groundMount, arg3: Variant_applianceBased_consumptionBased, arg4: number, arg5: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(arg0, to_candid_variant_n1(this._uploadFile, this._downloadFile, arg1), to_candid_variant_n2(this._uploadFile, this._downloadFile, arg2), to_candid_variant_n3(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(arg0, to_candid_variant_n1(this._uploadFile, this._downloadFile, arg1), to_candid_variant_n2(this._uploadFile, this._downloadFile, arg2), to_candid_variant_n3(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
    async createQuotation(arg0: string, arg1: string, arg2: string, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number, arg10: QuotationStatus, arg11: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createQuotation(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, to_candid_QuotationStatus_n4(this._uploadFile, this._downloadFile, arg10), arg11);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createQuotation(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, to_candid_QuotationStatus_n4(this._uploadFile, this._downloadFile, arg10), arg11);
            return result;
        }
    }
    async createUser(arg0: string, arg1: string, arg2: UserRole, arg3: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(arg0, arg1, to_candid_UserRole_n6(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(arg0, arg1, to_candid_UserRole_n6(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async getAuditLog(): Promise<Array<AuditEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuditLog();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuditLog();
            return result;
        }
    }
    async listBrands(): Promise<Array<Brand>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBrands();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBrands();
            return result;
        }
    }
    async listInventory(): Promise<Array<InventoryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listInventory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInventory();
            return result;
        }
    }
    async listMOQ(arg0: bigint): Promise<Array<MOQItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMOQ(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMOQ(arg0);
            return result;
        }
    }
    async listProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProjects();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProjects();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async listQuotations(): Promise<Array<Quotation>> {
        if (this.processError) {
            try {
                const result = await this.actor.listQuotations();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listQuotations();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async listUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMOQItem(arg0: bigint, arg1: number, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMOQItem(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMOQItem(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_ProjectStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectStatus): ProjectStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Project_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Project {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_QuotationStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuotationStatus): QuotationStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Quotation_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Quotation): Quotation {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_User_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    installationType: {
        sheetMetal: null;
    } | {
        rccRooftop: null;
    } | {
        other: null;
    } | {
        groundMount: null;
    };
    status: _ProjectStatus;
    batteryCapacityKWh: number;
    clientName: string;
    loadInputMethod: {
        applianceBased: null;
    } | {
        consumptionBased: null;
    };
    systemSizeKW: number;
    systemType: {
        hybrid: null;
    } | {
        offGrid: null;
    } | {
        onGrid: null;
    };
}): {
    id: bigint;
    installationType: Variant_sheetMetal_rccRooftop_other_groundMount;
    status: ProjectStatus;
    batteryCapacityKWh: number;
    clientName: string;
    loadInputMethod: Variant_applianceBased_consumptionBased;
    systemSizeKW: number;
    systemType: Variant_hybrid_offGrid_onGrid;
} {
    return {
        id: value.id,
        installationType: from_candid_variant_n11(_uploadFile, _downloadFile, value.installationType),
        status: from_candid_ProjectStatus_n12(_uploadFile, _downloadFile, value.status),
        batteryCapacityKWh: value.batteryCapacityKWh,
        clientName: value.clientName,
        loadInputMethod: from_candid_variant_n14(_uploadFile, _downloadFile, value.loadInputMethod),
        systemSizeKW: value.systemSizeKW,
        systemType: from_candid_variant_n15(_uploadFile, _downloadFile, value.systemType)
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    gst: number;
    irr: number;
    status: _QuotationStatus;
    subsidy: number;
    clientName: string;
    paybackYears: number;
    proposalNumber: string;
    totalCost: number;
    carbonSavings: number;
    annualSavings: number;
    termsAndConditions: string;
    companyName: string;
}): {
    id: bigint;
    gst: number;
    irr: number;
    status: QuotationStatus;
    subsidy: number;
    clientName: string;
    paybackYears: number;
    proposalNumber: string;
    totalCost: number;
    carbonSavings: number;
    annualSavings: number;
    termsAndConditions: string;
    companyName: string;
} {
    return {
        id: value.id,
        gst: value.gst,
        irr: value.irr,
        status: from_candid_QuotationStatus_n19(_uploadFile, _downloadFile, value.status),
        subsidy: value.subsidy,
        clientName: value.clientName,
        paybackYears: value.paybackYears,
        proposalNumber: value.proposalNumber,
        totalCost: value.totalCost,
        carbonSavings: value.carbonSavings,
        annualSavings: value.annualSavings,
        termsAndConditions: value.termsAndConditions,
        companyName: value.companyName
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    role: _UserRole;
    isActive: boolean;
    email: string;
}): {
    id: bigint;
    name: string;
    role: UserRole;
    isActive: boolean;
    email: string;
} {
    return {
        id: value.id,
        name: value.name,
        role: from_candid_UserRole_n24(_uploadFile, _downloadFile, value.role),
        isActive: value.isActive,
        email: value.email
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sheetMetal: null;
} | {
    rccRooftop: null;
} | {
    other: null;
} | {
    groundMount: null;
}): Variant_sheetMetal_rccRooftop_other_groundMount {
    return "sheetMetal" in value ? Variant_sheetMetal_rccRooftop_other_groundMount.sheetMetal : "rccRooftop" in value ? Variant_sheetMetal_rccRooftop_other_groundMount.rccRooftop : "other" in value ? Variant_sheetMetal_rccRooftop_other_groundMount.other : "groundMount" in value ? Variant_sheetMetal_rccRooftop_other_groundMount.groundMount : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: null;
} | {
    approved: null;
} | {
    quoted: null;
} | {
    draft: null;
} | {
    inProgress: null;
}): ProjectStatus {
    return "completed" in value ? ProjectStatus.completed : "approved" in value ? ProjectStatus.approved : "quoted" in value ? ProjectStatus.quoted : "draft" in value ? ProjectStatus.draft : "inProgress" in value ? ProjectStatus.inProgress : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    applianceBased: null;
} | {
    consumptionBased: null;
}): Variant_applianceBased_consumptionBased {
    return "applianceBased" in value ? Variant_applianceBased_consumptionBased.applianceBased : "consumptionBased" in value ? Variant_applianceBased_consumptionBased.consumptionBased : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hybrid: null;
} | {
    offGrid: null;
} | {
    onGrid: null;
}): Variant_hybrid_offGrid_onGrid {
    return "hybrid" in value ? Variant_hybrid_offGrid_onGrid.hybrid : "offGrid" in value ? Variant_hybrid_offGrid_onGrid.offGrid : "onGrid" in value ? Variant_hybrid_offGrid_onGrid.onGrid : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sent: null;
} | {
    rejected: null;
} | {
    accepted: null;
} | {
    draft: null;
}): QuotationStatus {
    return "sent" in value ? QuotationStatus.sent : "rejected" in value ? QuotationStatus.rejected : "accepted" in value ? QuotationStatus.accepted : "draft" in value ? QuotationStatus.draft : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    owner: null;
} | {
    procurement: null;
} | {
    siteEngineer: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "owner" in value ? UserRole.owner : "procurement" in value ? UserRole.procurement : "siteEngineer" in value ? UserRole.siteEngineer : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Quotation>): Array<Quotation> {
    return value.map((x)=>from_candid_Quotation_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Array<Project> {
    return value.map((x)=>from_candid_Project_n9(_uploadFile, _downloadFile, x));
}
function to_candid_QuotationStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuotationStatus): _QuotationStatus {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_hybrid_offGrid_onGrid): {
    hybrid: null;
} | {
    offGrid: null;
} | {
    onGrid: null;
} {
    return value == Variant_hybrid_offGrid_onGrid.hybrid ? {
        hybrid: null
    } : value == Variant_hybrid_offGrid_onGrid.offGrid ? {
        offGrid: null
    } : value == Variant_hybrid_offGrid_onGrid.onGrid ? {
        onGrid: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_sheetMetal_rccRooftop_other_groundMount): {
    sheetMetal: null;
} | {
    rccRooftop: null;
} | {
    other: null;
} | {
    groundMount: null;
} {
    return value == Variant_sheetMetal_rccRooftop_other_groundMount.sheetMetal ? {
        sheetMetal: null
    } : value == Variant_sheetMetal_rccRooftop_other_groundMount.rccRooftop ? {
        rccRooftop: null
    } : value == Variant_sheetMetal_rccRooftop_other_groundMount.other ? {
        other: null
    } : value == Variant_sheetMetal_rccRooftop_other_groundMount.groundMount ? {
        groundMount: null
    } : value;
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_applianceBased_consumptionBased): {
    applianceBased: null;
} | {
    consumptionBased: null;
} {
    return value == Variant_applianceBased_consumptionBased.applianceBased ? {
        applianceBased: null
    } : value == Variant_applianceBased_consumptionBased.consumptionBased ? {
        consumptionBased: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuotationStatus): {
    sent: null;
} | {
    rejected: null;
} | {
    accepted: null;
} | {
    draft: null;
} {
    return value == QuotationStatus.sent ? {
        sent: null
    } : value == QuotationStatus.rejected ? {
        rejected: null
    } : value == QuotationStatus.accepted ? {
        accepted: null
    } : value == QuotationStatus.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    owner: null;
} | {
    procurement: null;
} | {
    siteEngineer: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.owner ? {
        owner: null
    } : value == UserRole.procurement ? {
        procurement: null
    } : value == UserRole.siteEngineer ? {
        siteEngineer: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
